name: Update User Data
on:
  schedule:
    - cron: '0 0 * * *' # Запускать каждый день в полночь
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install axios

      - name: Update user data
        run: |
          node -e "
          const axios = require('axios');
          const fs = require('fs');

          axios.get('https://api.vk.com/method/users.get', {
            params: {
              user_ids: 8014332, // Замените на ID пользователя
              fields: 'email',
              access_token: 'ВАШ_ТОКЕН', // Замените на ваш токен
              v: '5.131'
            }
          })
          .then(response => {
            fs.writeFileSync('user-data.json', JSON.stringify(response.data));
          })
          .catch(error => {
            console.error('Ошибка при получении данных:', error);
          });
          "

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add user-data.json
          git commit -m 'Update user data'
          git push
